site_name: ksttt
site_description: A django implementation of Kriegspiel Tic-Tac-Toe https://www.smbc-comics.com/comic/tic
repo_url: https://github.com/rbarghou/django-kriegspiel-tick-tac-toe
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/rbarghou">rbarghou</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
