# Generated by Django 4.2.10 on 2024-02-16 15:23

from django.db import migrations, models
import kriegspiel_ttt.games.gameboard


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="game_data",
            field=models.JSONField(
                decoder=kriegspiel_ttt.games.gameboard.GameBoard.Decoder,
                default={},
                encoder=kriegspiel_ttt.games.gameboard.GameBoard.Encoder,
            ),
        ),
    ]
