# Generated by Django 4.2.10 on 2024-02-15 18:43

from django.db import migrations
import kriegspiel_ttt.games.models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="game_data",
            field=kriegspiel_ttt.games.models.GameDataField(default={}),
        ),
    ]
